# Generated by Django 5.0.4 on 2024-04-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_normal_price_food_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
