# Generated by Django 5.0.4 on 2024-04-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['pk'], 'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
    ]
