# Generated by Django 5.0.4 on 2024-05-10 18:23

import apps.utilities.paths
import apps.utilities.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=apps.utilities.paths.image_path)),
                ('banner', models.ImageField(blank=True, upload_to=apps.utilities.paths.image_banner_path)),
                ('description', models.TextField(blank=True)),
                ('specialty', models.CharField(choices=[('varied', 'Varied'), ('chilean', 'Chilean'), ('peruvian', 'Peruvian'), ('argentinian', 'Argentinian'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('french', 'French'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('thai', 'Thai'), ('spanish', 'Spanish'), ('russian', 'Russian'), ('moroccan', 'Moroccan'), ('korean', 'Korean'), ('turkish', 'Turkish')], default='varied', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('phone', models.CharField(max_length=12, unique=True, validators=[apps.utilities.validators.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True, max_length=255)),
                ('tiktok', models.URLField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('is_open', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['pk'],
            },
        ),
    ]
