# Generated by Django 5.0.4 on 2024-04-17 18:35

import apps.utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tiktok',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[apps.utilities.validators.validate_phone]),
        ),
    ]
