# Generated by Django 5.0.4 on 2024-05-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='comune',
            field=models.ForeignKey(default='a0d046df-2883-419d-8788-921c94cc6e77', on_delete=django.db.models.deletion.PROTECT, to='locations.comune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.ForeignKey(default='9b7414d3-cd3a-4a13-95e0-60a0042267b4', on_delete=django.db.models.deletion.PROTECT, to='locations.region'),
            preserve_default=False,
        ),
    ]
