# Generated by Django 5.0.4 on 2024-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='base price of the product, excluding taxes and surcharges.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, help_text='Total price plus taxes.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfood',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='base price of the product, excluding taxes and surcharges.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfood',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, help_text='Total price plus taxes.', max_digits=10),
        ),
    ]
