# Generated by Django 5.0.4 on 2024-08-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_food_price_alter_food_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_spicy',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='historicalfood',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='historicalfood',
            name='is_spicy',
        ),
        migrations.RemoveField(
            model_name='historicalfood',
            name='is_vegetarian',
        ),
    ]
