# Generated by Django 5.0.4 on 2024-04-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['pk'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
    ]
