# Generated by Django 5.0.4 on 2024-04-19 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0004_restaurant_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='comune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.comune'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('credit card', 'Credit Card'), ('debit card', 'Debit Card')], default='cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.region'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
