# Generated by Django 5.0.4 on 2024-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('credit card', 'Credit Card'), ('debit card', 'Debit Card')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('credit card', 'Credit Card'), ('debit card', 'Debit Card')], max_length=15),
        ),
    ]
