# Generated by Django 5.0.4 on 2024-07-30 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_historicalorder_is_payment_order_is_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
