# Generated by Django 5.0.4 on 2024-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalorder_is_valid_order_is_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='shipping_price',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='shipping_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
