# Generated by Django 5.0.4 on 2024-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_historicalorder_shipping_price_and_more'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order_id', 'food_id'), name='unique_order_food'),
        ),
    ]
