# Generated by Django 5.0.4 on 2024-08-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
