exclude: "^/migrations/"
default_stages: [commit]

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.16.0"
    hooks:
      - id: django-upgrade
        args: ["--target-version", "5.0"]

  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args: ["--max-line-length=79", "--ignore=E501,W503"]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
