// Drop Dash - Database Structure

// Ref: Playlist.user_id < User.id
// Ref: Playlist.Content_id < Content.id

// Utilities App

Table Base {
  id uuid [pk]
  available bool
  updated_at datetime
  created_at datetime
}

// Users App

Table User {
  id uuid [pk]
  email varchar(100) [unique]
  username varchar(100)
  slug slug [unique]
  first_name varchar(255)
  last_name varchar(255)
  date_birth date
  points int(0)
  is_active bool(true)
  is_staff bool(false)
  created_at date
  updated_at date
}

// Reviews App

Table Review {
  id uuid [pk]
  content_type FK
  object_id uuid
  content_object GFG
  user FK
  rating int
  comment text
  available base
  updated_at base
  created_at base
}

// Restaurants App

Table Restaurant {
  id uuid [pk]
  user FK
  name varchar(50)
  slug slug(50)
  image image
  banner image
  description text
  specialty varchar(20) CHOICES
  address varchar(255)
  city FK
  state FK
  country FK
  opening_time datetime
  closing_time datetime
  phone varchar(12)
  website url(255)
  is_open bool(false)
  is_verified bool(false)
  banking_certificate file
  e_rut file
  legal_rep_email file
  legal_rep_identity_document file
  legal_rep_power_of_attorney file
  available base
  updated_at base
  created_at base
}

Table Category {
  id uuid [pk]
  name varchar(100)
  restaurant FK
  available base
  updated_at base
  created_at base
}

Table Food {
  id uuid [pk]
  name
  description
  price
  sale_price
  image
  restaurant
  category
  is_vegetarian
  is_gluten_free
  is_spicy
  is_featured
  available base
  updated_at base
  created_at base
}

// Promotions App

Table Promotion {
  id uuid [pk]
  creator FK
  name
  conditions
  start_date
  end_date
  is_active
  image
  available base
  updated_at base
  created_at base
}

// Orders App

Table Order {
  id uuid [pk]
  available base
  user
  shipping_name
  shipping_phone
  shipping_time
  shipping_price
  transaction
  address_1
  address_2
  city
  state
  country
  note
  zip_code
  restaurant
  amount
  status
  payment_method
  updated_at base
  created_at base
}

Table OrderItem {
  id uuid [pk]
  order FK
  food FK
  price
  subtotal
  quantity
  available base
  updated_at base
  created_at base
}

// Locations App

Table Country {
  id uuid [pk]
  name varchar(100) [unique]
  available base
  updated_at base
  created_at base
}

Table State {
  id uuid [pk]
  name varchar(100) [unique]
  country FK
  available base
  updated_at base
  created_at base
}

Table City {
  id uuid [pk]
  name varchar(100) [unique]
  state FK
  available base
  updated_at base
  created_at base
}

// Drivers App

Table Driver {
  id uuid [pk]
  user
  phone
  birth_date
  driver_license
  identification_document
  social_security_certificate
  address
  city
  state
  country
  is_verified
  status
  available base
  updated_at base
  created_at base
}

Table Resource {
  id uuid [pk]
  driver FK
  resource_type varchar(15)
  note text
  status varchar(15)
  available base
  updated_at base
  created_at base
}


// Deliveries App

Table Delivery {
  id uuid [pk]
  // TODO: Add fields
  available base
  updated_at base
  created_at base
}


// Jobs App

Table Position {
  id uuid [pk]
  position varchar(100) [unique]
  description text
  available base
  updated_at base
  created_at base
}

Table Worker {
  id uuid [pk]
  user FK
  phone_number varchar(15)
  address varchar(255)
  city FK
  state FK
  country FK
  position FK
  hired_date date
  termination_date date
  hourly_rate decimal(10)
  contract_type varchar(15)
  contract_file file
  available base
  updated_at base
  created_at base
}

Table Applicant {
  id uuid [pk]
  user FK
  phone_number varchar(15)
  email email(100)
  applied_for FK
  cv file
  message text
  submitted_at datetime
  status varchar(10)
  available base
  updated_at base
  created_at base
}

// Blogs App

Table Tag {
  id uuid [pk]
  name varchar(50) [unique]
  slug slug [unique]
  available base
  updated_at base
  created_at base
}

Table Post {
  id uuid [pk]
  title
  slug
  content
  tags
  author
  points
  is_featured
  available base
  updated_at base
  created_at base
}

Table PostReport {
  id uuid [pk]
  user
  post
  reason
  priority
  status
  available base
  updated_at base
  created_at base
}
