# Generated by Django 5.0.4 on 2024-07-31 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the worker is currently active.'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_full_time',
            field=models.BooleanField(default=False, help_text='Indicates if the worker is employed full-time.'),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active'], name='jobs_worker_is_acti_e22e53_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_full_time'], name='jobs_worker_is_full_f44949_idx'),
        ),
    ]
