# Generated by Django 5.0.4 on 2024-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_fixeddiscountcoupon_fixedcoupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcoupon',
            name='code',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
