# Generated by Django 5.0.4 on 2024-04-18 20:07

import apps.coupons.validators
import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_fixedcoupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcoupon',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[apps.coupons.validators.validate_discount_price]),
        ),
        migrations.AlterField(
            model_name='fixedcoupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 18, 20, 7, 2, 451062, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fixedcoupon',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='code',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='discount_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 18, 20, 7, 2, 451822, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
