# Generated by Django 5.0.4 on 2024-04-22 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_fixedcoupon_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcoupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 16, 34, 16, 788467, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 16, 34, 16, 789227, tzinfo=datetime.timezone.utc)),
        ),
    ]
