# Generated by Django 5.0.4 on 2024-04-22 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_alter_fixedcoupon_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcoupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 17, 54, 21, 904424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 17, 54, 21, 905234, tzinfo=datetime.timezone.utc)),
        ),
    ]
