# Generated by Django 5.0.4 on 2024-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_fixedcoupon_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcoupon',
            options={'ordering': ['pk'], 'verbose_name': 'fixed coupon', 'verbose_name_plural': 'fixed coupons'},
        ),
        migrations.AlterModelOptions(
            name='percentagecoupon',
            options={'ordering': ['pk'], 'verbose_name': 'percentage coupon', 'verbose_name_plural': 'percentage coupons'},
        ),
        migrations.AlterField(
            model_name='fixedcoupon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fixedcoupon',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='percentagecoupon',
            name='start_date',
            field=models.DateField(),
        ),
    ]
