# Generated by Django 5.0.4 on 2024-05-24 21:34

import apps.utilities.paths
import apps.utilities.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_fixedcoupon_creator_percentagecoupon_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(upload_to=apps.utilities.paths.image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp']), apps.utilities.validators.ImageSizeValidator(max_height=1080, max_width=1080), apps.utilities.validators.FileSizeValidator(limit_mb=1)]),
        ),
    ]
