# Generated by Django 5.0.4 on 2024-05-14 16:07

import apps.utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(verbose_name=apps.utilities.validators.DateRangeValidator(days=90)),
        ),
    ]
