# Generated by Django 5.0.4 on 2024-08-14 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_alter_driverassignment_options_driver_is_active_and_more'),
        ('orders', '0009_remove_historicalorder_zip_code_and_more'),
        ('restaurants', '0003_remove_food_is_gluten_free_remove_food_is_spicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('delivery_earnings', 'Delivery Earnings'), ('restaurant_commission', 'Restaurant Commission'), ('driver_withdrawal', 'Driver Withdrawal'), ('promotional_bonus', 'Promotional Bonus'), ('referral_bonus', 'Referral Bonus'), ('other_income', 'Other Income'), ('expense', 'Expense'), ('adjustment', 'Adjustment'), ('marketing_expense', 'Marketing Expense'), ('operational_expense', 'Operational Expense'), ('subscription_revenue', 'Subscription Revenue'), ('partnership_revenue', 'Partnership Revenue'), ('refund', 'Refund'), ('taxes', 'Taxes'), ('loan_repayment', 'Loan Repayment')], max_length=30)),
                ('driver_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drivers.driver')),
                ('order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
                ('restaurant_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['order_id'], name='finances_re_order_i_b4cb88_idx'), models.Index(fields=['driver_id'], name='finances_re_driver__9d8cad_idx'), models.Index(fields=['restaurant_id'], name='finances_re_restaur_e4a447_idx'), models.Index(fields=['transaction_type'], name='finances_re_transac_57917d_idx')],
            },
        ),
    ]
