# Generated by Django 5.0.4 on 2024-08-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_resource_drivers_res_driver__47854d_idx_and_more'),
        ('finances', '0001_initial'),
        ('orders', '0009_remove_historicalorder_zip_code_and_more'),
        ('restaurants', '0003_remove_food_is_gluten_free_remove_food_is_spicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.restaurant'),
        ),
    ]
