# Generated by Django 5.0.4 on 2024-07-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_historicalfaileddelivery_faileddelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faileddelivery',
            options={'ordering': ['pk'], 'verbose_name': 'failed delivery', 'verbose_name_plural': 'failed deliveries'},
        ),
        migrations.AlterModelOptions(
            name='historicalfaileddelivery',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical failed delivery', 'verbose_name_plural': 'historical failed deliveries'},
        ),
    ]
