# Generated by Django 5.0.4 on 2024-04-16 17:49

import apps.drivers.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\+569\\d{8}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(validators=[apps.drivers.validators.validate_birth_date])),
                ('status', models.CharField(choices=[('bronce', 'Bronce'), ('silver', 'Silver'), ('diamond', 'Diamond'), ('alert', 'Alert')], default='bronce', max_length=10)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.comune')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
