# Generated by Django 5.0.4 on 2024-05-13 17:22

import apps.utilities.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[apps.utilities.validators.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(validators=[apps.utilities.validators.validate_birth_date])),
                ('status', models.CharField(choices=[('Bronce', 'Bronce'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Alert', 'Alert')], default='Bronce', max_length=10)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.comune')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['pk'],
            },
        ),
    ]
