# Generated by Django 5.0.4 on 2024-04-17 18:15

import apps.utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(validators=[apps.utilities.validators.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[apps.utilities.validators.validate_phone]),
        ),
    ]
