# Generated by Django 5.0.4 on 2024-04-17 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_birth_date_alter_driver_phone'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='comune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.comune'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.region'),
        ),
    ]
