# Generated by Django 5.0.4 on 2024-07-29 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverassignment'),
        ('locations', '0001_initial'),
        ('orders', '0003_historicalorder_is_payment_order_is_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'driver assignment', 'verbose_name_plural': 'driver assignments'},
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if the driver is active to receive orders.'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_verified', 'is_active'], name='drivers_dri_is_veri_de27e5_idx'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['status'], name='drivers_dri_status_2a37ee_idx'),
        ),
    ]
