# Generated by Django 5.0.4 on 2024-08-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driverassignment_options_driver_is_active_and_more'),
        ('orders', '0009_remove_historicalorder_zip_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['driver_id', 'resource_type'], name='drivers_res_driver__47854d_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverassignment',
            constraint=models.UniqueConstraint(fields=('driver_id', 'order_id'), name='unique_driver_order_assignment'),
        ),
        migrations.AddConstraint(
            model_name='driverassignment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'accepted', 'rejected'])), name='valid_assignment_status'),
        ),
    ]
