# Generated by Django 5.0.4 on 2024-04-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_comune_alter_driver_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['pk'], 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
