# Generated by Django 5.0.4 on 2024-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Bronce', 'Bronce'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Alert', 'Alert')], default='Bronce', max_length=10),
        ),
    ]
