# Generated by Django 5.0.4 on 2024-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='birth_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(),
        ),
    ]
